runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /stylesheets
  static_dir: stylesheets
- url: /.*
  script: engine.application
libraries:
- name: webapp2
  version: 2.5.2
- name: jinja2
  version: 2.6
- name: numpy
  version: "1.6.1"
skip_files:
- ml-25m/
- venv/
